import { NextRequest, NextResponse } from 'next/server'
import { createServiceRoleClient, validateToken } from '@/lib/supabase'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import { renderToBuffer } from '@react-pdf/renderer'
import React from 'react'

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Courier', fontSize: 10, color: '#1a1a1a', lineHeight: 1.5 },
  header: { marginBottom: 16 },
  title: { fontSize: 13, fontFamily: 'Courier-Bold', marginBottom: 4 },
  meta: { fontSize: 9, color: '#555', marginBottom: 2 },
  divider: { borderBottomWidth: 1, borderBottomColor: '#999', marginVertical: 12 },
  sectionTitle: { fontSize: 10, fontFamily: 'Courier-Bold', marginBottom: 4, marginTop: 8 },
  body: { fontSize: 10, marginBottom: 6 },
  statsRow: { flexDirection: 'row', gap: 16, marginBottom: 8 },
  statItem: { fontSize: 9 },
  cert: { fontSize: 9, color: '#444', lineHeight: 1.6 },
  pubItem: { marginBottom: 10 },
  pubTitle: { fontFamily: 'Courier-Bold', fontSize: 10 },
  pubMeta: { fontSize: 9, color: '#555' },
  pubReason: { fontSize: 9, fontStyle: 'italic' },
  footer: { fontSize: 8, color: '#888', marginTop: 4 },
})

function formatDate(iso: string) {
  return new Date(iso).toLocaleString('en-US', {
    month: 'short', day: '2-digit', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

function TrimPDF({ record, profile }: { record: Record<string, unknown>; profile: { full_name: string; institution: string } }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>GRANT ASSISTANT — EDITING COMPLIANCE REPORT</Text>
          <Text style={styles.meta}>Generated: {formatDate(new Date().toISOString())}</Text>
          <Text style={styles.meta}>Researcher: {profile.full_name || 'Unknown'}{profile.institution ? `, ${profile.institution}` : ''}</Text>
        </View>
        <View style={styles.divider} />

        <Text style={styles.body}>Grant Context: {(record.grant_title as string) || 'Not specified'}</Text>
        <Text style={styles.body}>ACTION TYPE: Text Trimming (Formatting Assistance Only)</Text>
        <Text style={styles.body}>Date: {formatDate(record.created_at as string)}</Text>

        <Text style={styles.sectionTitle}>CHARACTER COUNT</Text>
        <View style={styles.statsRow}>
          <Text style={styles.statItem}>Before: {record.char_count_before as number}</Text>
          <Text style={styles.statItem}>After: {record.char_count_after as number}</Text>
          <Text style={styles.statItem}>Limit: {record.char_limit as number}</Text>
        </View>

        <Text style={styles.sectionTitle}>SUMMARY</Text>
        <Text style={styles.body}>{record.diff_summary as string}</Text>

        <Text style={styles.sectionTitle}>ORIGINAL TEXT</Text>
        <Text style={styles.body}>{record.original_text as string}</Text>

        <Text style={styles.sectionTitle}>MODIFIED TEXT</Text>
        <Text style={styles.body}>{record.modified_text as string}</Text>

        <View style={styles.divider} />
        <Text style={styles.sectionTitle}>CERTIFICATION</Text>
        <Text style={styles.cert}>
          This document certifies that the scientific content, claims, citations, and{'\n'}
          numerical values in the text above were authored by the researcher. AI assistance{'\n'}
          was limited solely to removing words to meet a formatting character limit imposed{'\n'}
          by NIH SciENcv. No new scientific ideas, claims, or data were introduced by AI.
        </Text>
        <Text style={[styles.footer, { marginTop: 12 }]}>Generated by GrantAssistant | grantassistant.app</Text>
      </Page>
    </Document>
  )
}

function CitationPDF({ record, profile, totalSubmitted }: { record: Record<string, unknown>; profile: { full_name: string; institution: string }; totalSubmitted: number }) {
  const selected = (record.citations_selected as Array<{ pmid: string; title: string; reason: string }>) ?? []
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>GRANT ASSISTANT — CITATION SELECTION REPORT</Text>
          <Text style={styles.meta}>Generated: {formatDate(new Date().toISOString())}</Text>
          <Text style={styles.meta}>Researcher: {profile.full_name || 'Unknown'}{profile.institution ? `, ${profile.institution}` : ''}</Text>
        </View>
        <View style={styles.divider} />

        <Text style={styles.body}>Grant Context: {(record.grant_title as string) || 'Not specified'}</Text>
        <Text style={styles.body}>Action Date: {formatDate(record.created_at as string)}</Text>

        <Text style={styles.sectionTitle}>SELECTED PUBLICATIONS ({selected.length} of {totalSubmitted})</Text>

        {selected.map((pub, i) => (
          <View key={pub.pmid} style={styles.pubItem}>
            <Text style={styles.pubTitle}>{i + 1}. {pub.title}</Text>
            <Text style={styles.pubMeta}>PMID: {pub.pmid}</Text>
            <Text style={styles.pubReason}>Relevance: {pub.reason}</Text>
          </View>
        ))}

        <View style={styles.divider} />
        <Text style={styles.sectionTitle}>CERTIFICATION</Text>
        <Text style={styles.cert}>
          The researcher selected 5 publications from their own publication record for{'\n'}
          inclusion in an NIH biosketch. AI was used only to rank relevance based on the{'\n'}
          grant title provided. All listed publications are original works by the researcher.
        </Text>
        <Text style={[styles.footer, { marginTop: 12 }]}>Generated by GrantAssistant | grantassistant.app</Text>
      </Page>
    </Document>
  )
}

function AllRecordsPDF({ records, profile }: { records: Record<string, unknown>[]; profile: { full_name: string; institution: string } }) {
  return (
    <Document>
      {records.map((record) => {
        if (record.action_type === 'trim') {
          return (
            <Page key={record.id as string} size="A4" style={styles.page}>
              <View style={styles.header}>
                <Text style={styles.title}>GRANT ASSISTANT — EDITING COMPLIANCE REPORT</Text>
                <Text style={styles.meta}>Generated: {formatDate(new Date().toISOString())}</Text>
                <Text style={styles.meta}>Researcher: {profile.full_name || 'Unknown'}{profile.institution ? `, ${profile.institution}` : ''}</Text>
              </View>
              <View style={styles.divider} />
              <Text style={styles.body}>Grant Context: {(record.grant_title as string) || 'Not specified'}</Text>
              <Text style={styles.body}>ACTION TYPE: Text Trimming (Formatting Assistance Only)</Text>
              <Text style={styles.body}>Date: {formatDate(record.created_at as string)}</Text>
              <Text style={styles.sectionTitle}>CHARACTER COUNT</Text>
              <View style={styles.statsRow}>
                <Text style={styles.statItem}>Before: {record.char_count_before as number}</Text>
                <Text style={styles.statItem}>After: {record.char_count_after as number}</Text>
                <Text style={styles.statItem}>Limit: {record.char_limit as number}</Text>
              </View>
              <Text style={styles.sectionTitle}>SUMMARY</Text>
              <Text style={styles.body}>{record.diff_summary as string}</Text>
              <Text style={styles.sectionTitle}>ORIGINAL TEXT</Text>
              <Text style={styles.body}>{record.original_text as string}</Text>
              <Text style={styles.sectionTitle}>MODIFIED TEXT</Text>
              <Text style={styles.body}>{record.modified_text as string}</Text>
              <View style={styles.divider} />
              <Text style={styles.cert}>
                This document certifies that the scientific content, claims, citations, and numerical values in the text above were authored by the researcher. AI assistance was limited solely to removing words to meet a formatting character limit imposed by NIH SciENcv. No new scientific ideas, claims, or data were introduced by AI.
              </Text>
              <Text style={[styles.footer, { marginTop: 12 }]}>Generated by GrantAssistant | grantassistant.app</Text>
            </Page>
          )
        }

        const selected = (record.citations_selected as Array<{ pmid: string; title: string; reason: string }>) ?? []
        return (
          <Page key={record.id as string} size="A4" style={styles.page}>
            <View style={styles.header}>
              <Text style={styles.title}>GRANT ASSISTANT — CITATION SELECTION REPORT</Text>
              <Text style={styles.meta}>Generated: {formatDate(new Date().toISOString())}</Text>
              <Text style={styles.meta}>Researcher: {profile.full_name || 'Unknown'}{profile.institution ? `, ${profile.institution}` : ''}</Text>
            </View>
            <View style={styles.divider} />
            <Text style={styles.body}>Grant Context: {(record.grant_title as string) || 'Not specified'}</Text>
            <Text style={styles.body}>Action Date: {formatDate(record.created_at as string)}</Text>
            <Text style={styles.sectionTitle}>SELECTED PUBLICATIONS</Text>
            {selected.map((pub, i) => (
              <View key={pub.pmid} style={styles.pubItem}>
                <Text style={styles.pubTitle}>{i + 1}. {pub.title}</Text>
                <Text style={styles.pubMeta}>PMID: {pub.pmid}</Text>
                <Text style={styles.pubReason}>Relevance: {pub.reason}</Text>
              </View>
            ))}
            <View style={styles.divider} />
            <Text style={styles.cert}>
              The researcher selected 5 publications from their own publication record for inclusion in an NIH biosketch. AI was used only to rank relevance based on the grant title provided. All listed publications are original works by the researcher.
            </Text>
            <Text style={[styles.footer, { marginTop: 12 }]}>Generated by GrantAssistant | grantassistant.app</Text>
          </Page>
        )
      })}
    </Document>
  )
}

export async function GET(request: NextRequest) {
  const authHeader = request.headers.get('Authorization')
  const token = authHeader?.replace('Bearer ', '')
  if (!token) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const user = await validateToken(token)
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const supabase = createServiceRoleClient()

  // Fetch user profile for the PDF header
  const { data: profile } = await supabase
    .from('profiles')
    .select('full_name, institution')
    .eq('id', user.id)
    .single()

  const safeProfile = { full_name: profile?.full_name ?? '', institution: profile?.institution ?? '' }

  const url = new URL(request.url)
  const id = url.searchParams.get('id')
  const all = url.searchParams.get('all')

  let pdfBuffer: Buffer
  let filename: string

  if (all === 'true') {
    const { data: records, error } = await supabase
      .from('audit_records')
      .select('*')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })

    if (error) return NextResponse.json({ error: 'Failed to fetch records' }, { status: 500 })
    if (!records || records.length === 0) {
      return NextResponse.json({ error: 'No audit records found' }, { status: 404 })
    }

    pdfBuffer = await renderToBuffer(<AllRecordsPDF records={records} profile={safeProfile} />)
    filename = 'biotechos-all-records.pdf'
  } else if (id) {
    const { data: record, error } = await supabase
      .from('audit_records')
      .select('*')
      .eq('id', id)
      .eq('user_id', user.id)
      .single()

    if (error || !record) return NextResponse.json({ error: 'Record not found' }, { status: 404 })

    if (record.action_type === 'trim') {
      pdfBuffer = await renderToBuffer(<TrimPDF record={record} profile={safeProfile} />)
    } else {
      const totalSubmitted = Array.isArray(record.citations_selected) ? (record.citations_selected as unknown[]).length : 0
      pdfBuffer = await renderToBuffer(
        <CitationPDF record={record} profile={safeProfile} totalSubmitted={totalSubmitted} />
      )
    }
    filename = `biotechos-audit-${id.substring(0, 8)}.pdf`
  } else {
    return NextResponse.json({ error: 'Provide ?id=X or ?all=true' }, { status: 400 })
  }

  return new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}
